// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EFCoreRepro.Models
{
    public partial class Child
    {
        public long? Id { get; set; }
        public Guid? ParentId { get; set; }
        public Guid ChildId { get; set; }

        public virtual Parent Parent { get; set; }
    }
}