// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace EFCoreRepro.Models
{
    public partial class MMPContext : DbContext
    {
        public MMPContext()
        {
        }

        public MMPContext(DbContextOptions<MMPContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Child> Children { get; set; }
        public virtual DbSet<Parent> Parents { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Child>(entity =>
            {
                entity.ToTable("Child");

                entity.HasKey(e => e.Id); // Changing to  entity.HasKey(e => e.Id); works

                entity.HasIndex(e => e.Id, "AK_Child_ChildId")
                    .IsUnique();
                
                entity.Property(e => e.Id).HasColumnName("ChildId").HasDefaultValueSql("(newid())");

                entity.HasOne(d => d.Parent)
                    .WithMany(p => p.Children)
                    .HasPrincipalKey(p => p.Id)
                    .HasForeignKey(d => d.ParentId)
                    .HasConstraintName("FK_Child_ParentId");
            });

            modelBuilder.Entity<Parent>(entity =>
            {
                entity.ToTable("Parent");
                
                entity.HasKey(e => e.Id);

                entity.HasIndex(e => e.Id, "AK_Parent_ParentId")
                    .IsUnique();

                entity.Property(e => e.Id).HasColumnName("ParentId").HasDefaultValueSql("(newid())");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}